spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/muscle;MODE=MySQL
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace