name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Java App
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Add +x permission
        run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew clean build

      - name: Make application-prod.yml
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.YML_PROD }}" > ./application-prod.yml
        shell: bash

      - name: Upload jar file to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: ./app.jar
          retention-days: 1

      - name: Download Java App from Artifact
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        run: docker buildx build --platform linux/amd64,linux/arm64 -t inerplat/github-action-example:java${{ github.sha }} --push .

      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker stop mcpark
            docker rm mcpark
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            docker run -d --name mcpark -p 8000:8000 ${{ secrets.DOCKER_REPO }}
            docker rmi -f $(docker images -f "dangling=true" -q)
